src/main.c

Enter Energy Mode 1 in FreeRTOS idle hook.
Average current during integration tests:
- Without Energy Mode: 5,24mA
- With EM1: 3,99mA
It's hard to get better comparision as it's not so easy to automate gathering measurments
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/34)

Enable EM1 in idle hook

---

libs/base/Include/base/os.h
libs/drivers/comm/comm.c
libs/fs/Include/fs/fs.h
libs/fs/extension.c
libs/fs/fs.c
libs/logger/Logger.c
libs/os/os.c
libs/time/include/time/TimePoint.h
src/commands/file_system.c
src/main.c
unit_tests/mock/FsMock.cpp
unit_tests/mock/FsMock.hpp
unit_tests/os/os.cpp
unit_tests/time/persistance.cpp

* From now on all file system procedures receive pointer to FileSystem object as their first parameter to facilitate building abstraction layer over file system driver and allow much easier file system mocking,
* Separate operation status from context information returned by the
* open,
* read,
* write
* openDirectory
procedures. From now on they returned dedicated types with separatied operation status (OSResult) and context information (i.e. fileHandle, number of bytes transfered) instead of pure ints,
* Migrate from pure int return values to OSResults,
* Map most of the errno error codes to OSResult enumerator,
* Update interface of open file procedure to:
* separate file access mode (r, w, rw), from file opening mode,
* drop the mode parameter that was supposed to be hard coded and …

Much more strongly typed (and usable) file system interface.

---

libs/base/CMakeLists.txt
libs/base/Include/base/reader.h
libs/base/reader.cpp
libs/drivers/antenna/miniport.cpp
libs/drivers/comm/Include/comm/comm.h
libs/drivers/comm/comm.cpp
libs/time/timer.cpp
src/commands/comm.cpp
unit_tests/CMakeLists.txt
unit_tests/Comm/CommFrameTest.cpp
unit_tests/Comm/CommTest.cpp
unit_tests/TeleCommandHandling/TeleCommandHandlingTest.cpp
unit_tests/base/ReaderTest.cpp

* Migrate buffer reader to c++ object, 
* Communication module update.
* From now on the communication module will first query the frame for its size and then download from the hardware the necessary minimum number of bytes needed.
* Update CommFrame interface to use the someone else's memory buffer instead of its own fixed size array.
* Move the frame verification logic out of frame receive procedure to ensure that invalid frame content will block the frame receive path.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/62)

Comm get exact number of bytes from frame

---

libs/free_rtos_wrapper/os.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/70)

Fix converting RTOS ticks into duration

---

libs/base/Include/base/reader.h
libs/base/Include/base/writer.h
libs/base/reader.cpp
libs/base/writer.cpp
unit_tests/CMakeLists.txt
unit_tests/base/RapidTest.cpp
unit_tests/base/ReaderTest.cpp
unit_tests/base/WriterTest.cpp

Added implementation for reader & writer to handle 2's complement little endian 16- and 32-bit values.
Added RapidCheck tests for writer -> reader loop.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/72)

Reader & writer signed implementation

---

integration_tests/obc/SerialPortTerminal.py
integration_tests/obc/file_system.py
integration_tests/tests/test_fs.py
libs/drivers/leuart/Include/leuart/line_io.h
libs/drivers/leuart/leuart.cpp
libs/fs/Include/fs/fs.h
libs/fs/Include/fs/yaffs.h
libs/fs/extension.cpp
libs/fs/yaffs.cpp
libs/terminal/include/terminal/terminal.h
libs/terminal/terminal.cpp
src/commands/antenna.cpp
src/commands/comm.cpp
src/commands/file_system.cpp
src/commands/i2c_test_command.cpp
unit_tests/mock/FsMock.hpp

Currently `writeFile` and `readFile` commands are very limited. It is possible to write file command must fit into input buffer (100 bytes) with `writeFile path content` also it is not possible to write new line character as it will terminate command line reading. Simillary reading file that contains prompt (`>`) character will terminate reading file on Python side and lead to unusable terminal access.
This pull requests modifes `writeFile` and `readFile` commands to overcome this issues by:
* Writing file in chunks
* Reading exact number of bytes for terminal and not relaying on any special character
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/71)

Change FS terminal commands to allow operating on any file

---

integration_tests/devices/__init__.py
integration_tests/devices/antenna.py
integration_tests/devices/comm.py
integration_tests/i2cMock/i2cMock.py
integration_tests/obc/__init__.py
integration_tests/obc/antenna.py
integration_tests/obc/comm.py
integration_tests/tests/test_antenna.py
integration_tests/tests/test_comm.py
integration_tests/utils.py
src/commands/antenna.cpp
src/commands/comm.cpp
src/commands/commands.h
src/terminal.cpp

Terminal commands for testing comm & antenna hardware/drivers.
* New commands:
* antenna_get_telemetry
* antenna_reset [primary|backup]
* comm_get_telemetry [transmitter|receiver]
* comm_set_bitrate [1200|2400|4800|9600]
* Some integration tests for new commands
* Extended integration tests documentation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/73)

Test commands

---

integration_tests/devices/antenna.py
integration_tests/devices/comm.py
integration_tests/i2cMock/i2cMock.py
libs/drivers/antenna/Include/antenna/antenna.h
libs/drivers/comm/Include/comm/comm.hpp
libs/drivers/i2c/Include/i2c/i2c.h
libs/drivers/i2c/efm.cpp
unit_tests/Comm/CommTest.cpp

After physical tests it turned out that adresses in ICDs are 7-bit value without read/write marker padding.
Therefore, meaning of I2CAdress in I2C interface was changes to reflect 7-bit adress standard.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/77)

Changed meaning for I2C adress to 7-bit value

---

src/CMakeLists.txt
toolchain.cmake
unit_tests/CMakeLists.txt
utils/Attach.launch.template
utils/QEmu.launch.template
utils/Run.launch.template
utils/attach.launch.template
utils/functions.cmake
utils/run.launch.template

Allows generating Eclipse debug configurations as part of CMake build. 
Builds are named:
* `[Run] <target>` - Runs target with initial flashing
* `[Attach] <target>` - Attaches to running target
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/80)

Generate eclipse debug target as part of CMake build

---

unit_tests/CMakeLists.txt
unit_tests/I2C/I2CMock.cpp
unit_tests/I2C/I2CMock.hpp
unit_tests/OsMock.cpp
unit_tests/OsMock.hpp
unit_tests/mock/FsMock.cpp
unit_tests/mock/FsMock.hpp

According to https://github.com/google/googletest/blob/master/googlemock/docs/CookBook.md#making-the-compilation-faster it is wise to define constructor and destructor of mock class in single .cpp file to speed up compilation.
On my machine, command: `make -C unit_tests clean all -j5`
Before: ~67s
After: ~57s
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/87)

Speed up unit tests compilation

---

libs/drivers/burtc/Include/burtc/burtc.hpp
platforms/DevBoard/Include/FreeRTOSConfig.h
src/fault_handlers.cpp
src/main.cpp

Problem was caused by burtc task stack overflow that  occurred due to time service saving the current time to flash memory a process that requires ~2KB of stack space in total. 
Additionally stack overflow checking has been permanently enabled in debug builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/90)

Fix obc crash after first time update

---

libs/drivers/burtc/Include/burtc/burtc.hpp
libs/drivers/burtc/burtc.cpp
libs/time/include/time/timer.h
src/main.cpp

When external flash is enabled BURTC task tried to invoke time action
before Time Provider was initialized. That caused RTOS assert failures as queue
was not created yet.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/92)

Fixed RTOS errors in Time Provider

---

integration_tests/i2cMock/i2cMock.py

Integration tests mocks were wrong about device addresses and reported invalid commands when device was missing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/102)

Fixed i2cMock logs

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/Include/comm/IBeaconController.hpp
libs/drivers/comm/comm.cpp
libs/mission/beacon/BeaconUpdate.cpp
unit_tests/Comm/CommTest.cpp
unit_tests/MissionPlan/TimeTaskTest.cpp
unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp
unit_tests/mock/comm.hpp

Update beacon setting procedure to ensure that setting beacon will not cause
transmitter to remove any frames from the outgoing frame buffer before they
are send. This is done by first sending beacon as a regular frame and checking
the number of transmitter''s output buffer free slot count.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/107)

[comm] Prevent beacon update from erasing frames from transmitter queue

---

integration_tests/tests/test_experiment_detumbling.py

In detumbling experiment test, experiment was commanded to run for 4
hours. After that OBC time was advanced also by 4 hours, however it was
not enough as during next mission loop OBC time was few milliseconds
before scheduled experiment end.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/119)

Fix race condition in detumbling experiment test

---

libs/base/Include/base/os.h
libs/drivers/comm/comm.cpp
libs/free_rtos_wrapper/os.cpp
libs/mission/Include/mission/main.hpp
libs/terminal/include/terminal/terminal.h
src/commands/rtos_status.cpp
src/main.cpp

`xTaskCreate` expects parameter with size of the stack for new task in **words**. However size of the **word** is port-dependent and in case of Cortex-M3 its 4 bytes not 2 as we assumed at the begining. 
This change hides calculation of size in words by doing the division just before calling `xTaskCreate` and using size of `StackType_t`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/125)

You've been calculating your stack size WRONG whole time - click here to see why!

---

integration_tests/obc/obc.py
libs/drivers/burtc/Include/burtc/burtc.hpp
src/CMakeLists.txt
src/commands/comm.cpp
src/commands/commands.h
src/commands/obc_state.cpp
src/main.cpp
src/obc.cpp
src/obc.h
src/terminal.cpp

Changed busy wait for OBC initialization finish from Python tests into RTOS wait on the OBC side. Not very much but cuts about a minute from build time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/124)

No busy waiting for OBC startup

---

libs/mission/Include/mission/base.hpp
libs/mission/Include/mission/logic.hpp
libs/mission/adcs/Include/mission/adcs.hpp
libs/mission/adcs/adcs.cpp
libs/mission/antenna/antenna.cpp
libs/mission/beacon/BeaconUpdate.cpp
libs/mission/beacon/Include/mission/BeaconUpdate.hpp
libs/mission/experiments/Include/mission/experiments.hpp
libs/mission/experiments/experiments.cpp
libs/mission/sail/Include/mission/sail.hpp
libs/mission/sail/sail.cpp
libs/mission/state/Include/mission/PersistentStateSave.hpp
libs/mission/state/PersistentStateSave.cpp
libs/mission/telemetry/Include/mission/telemetry.hpp
libs/mission/telemetry/telemetry.cpp
libs/mission/time/Include/mission/time.hpp
libs/mission/time/time.cpp
libs/state/Include/state/struct.h
unit_tests/base/Include/mock/ActionDescriptorMock.hpp

Recent additions to obc's state showed that there are cases when actions also
have to change (although in a very limited way) obc state.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/145)

Drop the const qualifier from the state parameter of Action Descriptor action procedure.

---

Jenkinsfile
boot/comms.cpp
boot/comms.h
integration_tests/tests/test_telecommands_comm.py
src/commands/dma.cpp
test/fm_terminal/CMakeLists.txt
unit_tests/CMakeLists.txt

EM is now connected to CI machine. This pull requests changes CI builds to use FlightModel platform instead of DevBoard.
Older branches (with DevBoard CI build) will still work - both environments are available
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/148)

Use FlightModel platform on CI builds

---

test/fm_terminal/CMakeLists.txt
test/fm_terminal/fault_handlers.cpp
test/fm_terminal/main.cpp

FM terminal program was missing UART1_RX interrupt handler.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/156)

Fix FM terminal

---

libs/drivers/n25q/redundant_n25q.cpp

`memcmp` is about 45 times faster than span compare
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/159)

use memcmp for TMR compare instead of span compare

---

integration_tests/extensions/__init__.py
integration_tests/extensions/report_progress.py
integration_tests/requirements.txt
libs/efm_support/efm_emlib/emlib.cpp
src/obc.cpp
tools/pytests.cmd.template

Internal watchdog was enabled in runlevel 1 and time service was enabled in runlevel 2. That mismatch caused OBC to restart after ~1 minute.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/200)

Watchdog fix

---

integration_tests/i2cMock/i2cMock.py
integration_tests/tests/test_antenna_deployment.py
libs/mission/antenna/Include/mission/antenna_state.h
libs/mission/antenna/antenna.cpp
unit_tests/mission/MissionPlan/antenna/AntennaMissionStateTest.cpp
unit_tests/mission/MissionPlan/antenna/DeployAntennasTest.cpp

Harden antenna deployment against situation when hardware either does not respond at all or tries to lie and consistently insists that deployment process is always in progress.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/213)

Updated antenna deployment algorithm

---

platforms/mcu/EngModel/Include/mcu/io_map.h
platforms/mcu/FlightModel/Include/mcu/io_map.h

IO map fix - payload pfm 1.01 and 2.02 have wrong pin naming details can be found here: https://team.pw-sat.pl/F5527 and https://team.pw-sat.pl/w/pld/pfm/#important-issue-for-both)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/234)

IO map fix - payload pfm 1.01 and 2.02 have wrong pin naming

---

src/commands/eps.cpp

0xFFFF was printed as -1 in OBC terminal (long uint conversion to long int). This number should be printed as 4294967295. The %lu instead of %ld printf specifier fixes this issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/252)

EPS HK/UPTIME printf specifier fix in OBC terminal

---

integration_tests/experiment_file/__init__.py
integration_tests/experiment_file/base.py
integration_tests/experiment_file/gyro.py
integration_tests/experiment_file/suns.py
integration_tests/requirements.txt
integration_tests/tools/read_exp_file.py
libs/drivers/suns/Include/suns/suns.hpp
libs/experiments/suns/suns.cpp
test/CMakeLists.txt
test/generate_exp_data/CMakeLists.txt
test/generate_exp_data/main.cpp
test/generate_exp_data/suns_data.cpp
unit_tests/properties/Experiments/SunSDataPointTest.cpp

1) Fix for SunS experiment data (one temperature was missing)
2) Experiment file parser. Sample output:
```
Parsed data:
'Synchronization'
{'time': datetime.timedelta(0, 1, 234000)}
{'ExpSunS.Primary': {'Status': {'ALS_ACK': 13107,
'ALS_ADC_Valid': 8738,
'ALS_Presence': 4369},
'Temperatures': {'A': 30583,
'B': 34952,
'C': 39321,
'D': 43690,
'Structure': 26214},
'VisibleLight': [[41120, 41377, 41634, 41891],
[45232, 45489, 45746, 46003],
[49344, 49601, 49858, 50115]],
'WhoAmI ': 17}}
{'RefSunS': {'Volatages': [57568, 57825, 58082, 58339, 58596]}}
{'Gyro': {'Temperature': 28543, 'X': 3871, 'Y': 12095, 'Z': 20319}}
{'Padding': 159}
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Experiment file parser

---

libs/experiments/sail/sail.cpp

Necessary in case of delays caused by the communication problems.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/267)

[experiments][sail] Purge pending photo service commands at the end of experiment.

---

integration_tests/emulator/beacon.py
integration_tests/emulator/beacon_parser/parser.py
integration_tests/emulator/beacon_parser/time_state.py
integration_tests/emulator/comm.py
integration_tests/emulator/gui.fbp
integration_tests/emulator/gui.xrc
integration_tests/experiment_file/base.py
integration_tests/ipython_profile/startup/03-emulator.py

- Added transmitter simulator. When it is enabled it gets one by one frame from the queue.
- Mission Time and External time is converted to readable string.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/295)

[Emulator Addons] Simulated frame sending and parsing time.

---

integration_tests/devices/comm.py
integration_tests/obc/experiments.py
integration_tests/tests/test_experiment_sail.py

Fixed test failures caused by:
- wait_for_experiment_iteration skipping target iterations.
- COMM stall detection removing queued messages.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/303)

Fixed test failures inside Test Experiment Sail Autosend

---

platforms/mcu/FlightModel/Include/mcu/io_map.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/314)

OBC FM pinout fix (PD7 and PD5 in datasheet ver. 0.9 are swapped)

---

src/obc.cpp

Primary and secondary antenna error counters does not cause power cycle.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/338)

Masked antennas error counters

---

integration_tests/devices/adcs.py
integration_tests/obc/adcs.py
libs/adcs/AdcsCoordinator.cpp
libs/adcs/Include/adcs/AdcsCoordinator.hpp
libs/adcs/Include/adcs/adcs.hpp
libs/experiments/sads/sads.cpp
libs/experiments/sail/sail.cpp
libs/mission/adcs/adcs.cpp
libs/obc/adcs/Include/obc/adcs.hpp
libs/obc/adcs/adcs.cpp
src/commands/adcs.cpp
src/obc.cpp
unit_tests/base/Include/mock/AdcsMocks.hpp
unit_tests/mission/Experiments/Sail/SailExperimentTest.cpp
unit_tests/mission/MissionPlan/adcs/AdcsPrimaryTaskTest.cpp
unit_tests/others/adcs/AdcsCoordinatorTest.cpp

* Fix race condition between currently run processor & stop method,
* Fix race condition that could cause adcs task to be suspended indefinatelly,
* Add possibility to temporarily disable entire adcs subsystem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/335)

[adcs] Update adcs coordinator.

---

integration_tests/tests/test_antenna.py
src/obc.cpp

This should fix [NCR#037](https://team.pw-sat.pl/w/ncr/ncr37/).
Antennas are powered off by default, so resetting controllers won't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/349)

Remove antennas reset at bootup (they are powered off)

---

libs/experiments/payload/payload_exp.cpp
libs/photo/photo_service.cpp
unit_tests/mission/Experiments/payload/PayloadExperimentTest.cpp

Added:
* `6 s` delay after turning off the camera in photoservice
* `6 s` between steps in payload commissioning experiment
This should fix [NCR#041](https://team.pw-sat.pl/w/ncr/ncr41/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/350)

Added delays for power operations

---

libs/experiments/sads/sads.cpp

* Add delay after enabling sens lcl
* At the end of the experiment wait until photo service finishes its work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/357)

[experiments][sads] Update experiment definition

---

libs/mission/sail/Include/mission/sail.hpp
libs/mission/sail/sail.cpp
unit_tests/mission/MissionPlan/sail/OpenSailTest.cpp

If `IgnoreOverheat` and `EnableMainThermalKnife` are send simultaneously there is a possiblity of race condition when:
- overheat was detected, so turning off LCLs
- in the middle, interrupt is server to disable overheat mode (but on-going check is still going)
- then, before end, TK is enabled and immediatelly disabled by overheat protection.
This event is very unlikely (there is a window of about 2ms each second, and those two command would have to be send with less than 2ms interval. However fix was simple and should be enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/361)

Delay after turning on overheat mode

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
libs/obc/communication/communication.cpp
test/generate_persistent_state/main.cpp
unit_tests/drivers/Comm/CommTest.cpp

After hardware reset of COMM delay is necessary - hardware reset performs power cycle of COMMs module and it takes some time to initialise.
Moved resetting COMM to `OBCCommunication::InitializeRunlevel1`.
[NCR#13](https://team.pw-sat.pl/w/ncr/ncr13/)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/367)

Wait for COMM bootup

---

integration_tests/devices/suns.py
integration_tests/telecommand/i2c.py

Ensure that RawI2C command follows convention regarding the correllation_id
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/398)

Minor telecommand fixes

---

integration_tests/emulator/comm_zmq_adapter.py
integration_tests/tools/just_mocks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/400)

Allow setting of non-default GRC host/port in zmq device mock adapter
