.gitignore
integration_tests/CMakeLists.txt
integration_tests/ipython_profile/ipython_config.py
integration_tests/ipython_profile/startup/01-log-wx.py
integration_tests/ipython_profile/startup/02-obc.py
integration_tests/system/system.py
toolchain.cmake

Interactive console based on ipython allowing live interacting with OBC using the same API in tests (by `system` variable)
Log output is shown in separate window (wxWidgets).
Make target: `pyconsole`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/45)

Interactive console based on ipython

---

unit_tests/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/48)

Exclude unit tests and external libraries from code coverage

---

platforms/DevBoard/Include/FreeRTOSConfig.h
src/CMakeLists.txt
src/commands/commands.h
src/commands/rtos_status.cpp
src/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/54)

tasklist terminal command

---

doc/IntegrationTests.md
doxyfile
libs/base/Include/utils.h
libs/drivers/i2c/Include/i2c/efm.h

* Update doxygen configuration file to make it more suitable for c++,
* Fix some doxygen issues,
* Fix typo in the project documentation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/60)

Documentation update

---

libs/external/googletest/CMakeLists.txt
libs/external/googletest/CMakeLists.txt.in
libs/external/rapidcheck/CMakeLists.txt
libs/external/rapidcheck/CMakeLists.txt.in
unit_tests/CMakeLists.txt

Updated the way that googletest & rapidcheck are included into the project.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/68)

Build update

---

doc/IntegrationTests.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/75)

added pyconsole example

---

src/commands/commands.h
src/commands/ping.cpp
src/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/86)

Add command for resetting mcu from terminal.

---

libs/base/Include/base/os.h
libs/base/os_base.cpp
libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
libs/drivers/spi/Include/spi/efm.h
libs/drivers/spi/efm.cpp
unit_tests/CMakeLists.txt
unit_tests/os/EventGroupTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/83)

EventGroup wrapper

---

integration_tests/tests/test_fs.py
libs/obc/hardware/Include/obc/gpio.h
libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h
libs/obc/storage/n25q_flash/n25q.cpp
platforms/DevBoard/Include/io_map.h
src/main.cpp

Mount 3 external flashes when using N25Q storage
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/85)

Mount 3 external N25Q flashes

---

integration_tests/devices/__init__.py
integration_tests/devices/rtc.py
integration_tests/system/system.py
integration_tests/tests/test_experiment_detumbling.py
libs/drivers/rtc/Include/rtc/rtc.hpp
libs/mission/time/CMakeLists.txt
libs/mission/time/Include/mission/time.hpp
libs/mission/time/time.cpp
libs/time/include/time/timer.h
libs/time/timer.cpp
src/commands/rtc.cpp
src/commands/time.cpp
src/main.cpp
src/obc.cpp
src/obc.h
unit_tests/CMakeLists.txt
unit_tests/MissionPlan/TimeTaskTest.cpp
unit_tests/mock/RtcMock.hpp
unit_tests/time/SmartWait.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/99)

Implemented time correction based on external RTC

---

integration_tests/devices/rtc.py
integration_tests/obc/obc_time.py
integration_tests/tests/test_time.py
libs/drivers/rtc/Include/rtc/rtc.hpp
src/commands/rtc.cpp
unit_tests/CMakeLists.txt
unit_tests/time/rtc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/103)

Added time correction integration tests and reader unit tests

---

libs/mission/time/Include/mission/time.hpp
libs/mission/time/time.cpp
unit_tests/MissionPlan/TimeTaskTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/104)

Added MaximumTimeCorrection treshold

---

integration_tests/obc/SerialPortTerminal.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/108)

Ensure that 4 bytes are read from serial port

---

integration_tests/i2cMock/__init__.py
integration_tests/i2cMock/i2cMock.py
integration_tests/tests/test_i2c.py
src/commands/i2c_test_command.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/109)

Update for DeviceMock to support COMM i2c

---

unit_tests/adcs_experiments/detumblingTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/111)

stepDetunbling() needs 3 parameters - fixed

---

integration_tests/devices/antenna.py
integration_tests/tests/base.py
integration_tests/tests/test_antenna_deployment.py
integration_tests/tests/test_beacon.py
libs/drivers/antenna/miniport.cpp
libs/mission/adcs/adcs.cpp
libs/mission/antenna/Include/mission/antenna_state.h
libs/mission/antenna/antenna.cpp
libs/mission/beacon/BeaconUpdate.cpp
libs/state/Include/state/struct.h
unit_tests/MissionPlan/adcs/AdcsPrimaryTaskTest.cpp
unit_tests/MissionPlan/antenna/AntennaMissionStateTest.cpp
unit_tests/MissionPlan/antenna/DeployAntennasTest.cpp
unit_tests/MissionPlan/beacon/BeaconUpdateTest.cpp

Based on recent discussion & simplification.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/110)

Updated version of antenna deployed algorithm

---

integration_tests/tests/test_time.py
libs/drivers/rtc/Include/rtc/rtc.hpp
unit_tests/time/rtc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/115)

Fixed off by one error in RTC time encoding

---

integration_tests/devices/comm.py
integration_tests/obc/comm.py
integration_tests/tests/test_comm.py
src/commands/comm.cpp
src/commands/commands.h
src/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/117)

Terminal command: set comm idle state

---

src/CMakeLists.txt
src/commands/commands.h
src/commands/external_flash.cpp
src/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/121)

Commands for testing external flashes

---

doc/tc_list.md
doxyfile
libs/drivers/imtq/imtq.cpp
libs/drivers/rtc/Include/rtc/rtc.hpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/telecommands/Include/obc/telecommands/experiments.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/ping.hpp
libs/obc/communication/telecommands/file_system.cpp
unit_tests/Comm/Telecommands/DownloadFileTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/126)

Single page with list of all telecommands

---

src/commands/fram.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/122)

Commands for testing FRAMs

---

integration_tests/tests/test_experiments.py
libs/drivers/comm/comm.cpp
libs/experiments/Include/experiments/experiments.h
libs/experiments/experiments.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/131)

Fix stack sizes

---

doc/Runlevels.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/116)

Documented runlevels design

---

integration_tests/telecommand/experiments.py
integration_tests/tests/test_experiments.py
integration_tests/tests/test_telecommands_experiments.py
libs/base/Include/traits.hpp
libs/experiments/experiments.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/experiments.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/ping.hpp
libs/obc/communication/telecommands/experiments.cpp
libs/obc/communication/telecommands/file_system.cpp
libs/obc/communication/telecommands/ping.cpp
libs/telecommunication/include/telecommunication/telecommand_handling.h
test/flash/main.cpp
test/pulse_all/main.cpp
unit_tests/Experiments/ExperimentTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/134)

Telecommand: abort experiment

---

integration_tests/devices/eps.py
integration_tests/obc/error_counters.py
integration_tests/obc/obc.py
integration_tests/tests/test_eps.py
libs/base/Include/traits.hpp
libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/eps/CMakeLists.txt
libs/drivers/eps/Include/eps/eps.h
libs/drivers/eps/eps.cpp
libs/obc/hardware/Include/obc/hardware.h
libs/obc/hardware/hardware.cpp
src/CMakeLists.txt
src/checks/error_counters.cpp
src/commands/commands.h
src/commands/error_counters.cpp
src/obc.cpp
src/terminal.cpp
unit_tests/EPS/EPSDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/133)

EPS error counters

---

src/commands/file_system.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/136)

Fixed compilation error when compiling for STK Storage

---

libs/mission/time/time.cpp
unit_tests/state/state/PersistentTimeStateTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/137)

fixing header paths names due to compilation issues on linux

---

doc/CodingStyle.md
doc/mission_task_list.md
doc/persistent_state.md
doc/telemetry.md
doxyfile
libs/mission/adcs/Include/mission/adcs.hpp
libs/mission/antenna/Include/mission/antenna_task.hpp
libs/mission/beacon/Include/mission/BeaconUpdate.hpp
libs/mission/experiments/Include/mission/experiments.hpp
libs/mission/sail/Include/mission/sail.hpp
libs/mission/state/Include/mission/PersistentStateSave.hpp
libs/mission/telemetry/Include/mission/telemetry.hpp
libs/mission/time/Include/mission/time.hpp
libs/state/Include/state/antenna/AntennaConfiguration.hpp
libs/state/Include/state/time/TimeCorrectionConfiguration.hpp
libs/state/Include/state/time/TimeState.hpp

* Add dedicated page with list of mission tasks
* Add dedicated page with list of telemetry elements
* Add dedicated page with list of parsistent state parts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/144)

Extend doxygen generated documentation.

---

.gitignore
integration_tests/telecommand/__init__.py
integration_tests/telecommand/fs.py
integration_tests/tests/test_telecommands_fs.py
libs/fs/Include/fs/fs.h
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/file_system.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/DownloadFileTelecommandTest.cpp
unit_tests/communication/Telecommands/RemoveFileTelecommandTest.cpp

I had to increase stack size for `CommTask` from 2kB to 4kB because of failing integration tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/130)

[TeleComm] Added RemoveFile command

---

libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/file_system.cpp
platforms/DevBoard/settings.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/140)

[TeleComm] Refactored DownloadFile command

---

unit_tests/state/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/150)

[CI] Run state unit tests on Jenkins.

---

boot/commands/booting.cpp
boot/commands/commands.hpp
boot/comms.cpp
libs/base/Include/redundancy.hpp
src/commands/commands.h
src/commands/ping.cpp
src/terminal.cpp
tools/CMakeLists.txt
tools/download_mem_range.cmd.template
tools/flash-structure.h

Mechanism for booting application with TMR.
For now just building block with hardcoded slots 1,2,3, does not affect normal booting process
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/147)

Bootloader support for application TMR

---

doc/tools.md
integration_tests/tools/run_qemu.py
tools/CMakeLists.txt
tools/pytests.cmd.template
tools/unit_tests.cmd.template

Tools:
* `<build>/tools/unit_tests.cmd <binary> <args>` - running unit tests using QEMU
* `<build>/tools/pytests.cmd <args>` - running python tests (all required configuration is passed as it should be)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/153)

Tools for running unit tests & python tests from cmdline

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
unit_tests/drivers/Comm/CommTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/157)

Change comm loop timings

---

integration_tests/obc/fram.py
integration_tests/obc/obc.py
integration_tests/obc/obc_mixin.py
integration_tests/tests/test_tmr.py
libs/drivers/fm25w/Include/fm25w/fm25w.hpp
libs/drivers/fm25w/fm25w.cpp
libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp
libs/obc/hardware/Include/obc/hardware.h
libs/obc/hardware/PersistentStorageAccess.cpp
libs/obc/hardware/hardware.cpp
src/commands/fram.cpp
unit_tests/drivers/CMakeLists.txt
unit_tests/drivers/FM25W/RedundantFM25WDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/155)

Redundant fm25w driver

---

libs/adcs/experimental/Include/adcs/Detumbling.hpp
libs/base/Include/redundancy.hpp
libs/drivers/fm25w/Include/fm25w/fm25w.hpp
libs/mission/fs/Include/mission/fs.hpp
libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/163)

Fixes for various doxygen issues.

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/fs.py
integration_tests/tests/test_telecommands_fs.py
libs/external/yaffs/src/yaffsfs.c
libs/external/yaffs/src/yaffsfs.h
libs/fs/Include/fs/fs.h
libs/fs/Include/fs/yaffs.h
libs/fs/yaffs.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/comm.cpp
libs/obc/communication/telecommands/file_system.cpp
libs/telecommunication/downlink.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/base/Include/mock/FsMock.hpp
unit_tests/base/mock/FsMock.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/ListFilesTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/161)

List files telecommand

---

integration_tests/tests/test_fs.py
integration_tests/tests/test_tmr.py
libs/boot_params/Include/boot/params.hpp
libs/boot_params/params.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/166)

Fix TMR tests

---

libs/error_counter/Include/error_counter/error_counter.hpp
libs/telemetry/CMakeLists.txt
libs/telemetry/ErrorCounters.cpp
libs/telemetry/Include/telemetry/ErrorCounters.hpp
libs/telemetry/Include/telemetry/fwd.hpp
libs/telemetry/Include/telemetry/state.hpp
libs/telemetry/fdir/CMakeLists.txt
libs/telemetry/fdir/Include/telemetry/collect_fdir.hpp
libs/telemetry/fdir/collect_fdir.cpp
src/CMakeLists.txt
src/main.cpp
src/mission.h
unit_tests/drivers/gyro/GyroTelemetryTest.cpp
unit_tests/state/CMakeLists.txt
unit_tests/state/telemetry/ErrorCountingTelemetryTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/172)

[telemetry] Extend telemetry acquisition of error counters state

---

libs/drivers/comm/comm.cpp
unit_tests/drivers/Comm/CommTest.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/174)

[comm] Add verification that incoming number of frames does not exceed hardware limit

---

libs/adcs/experimental/Include/adcs/Detumbling.hpp
libs/base/Include/base/BitWriter.hpp
libs/base/Include/utils.h
libs/drivers/comm/Include/comm/CommTelemetry.hpp
libs/drivers/eps/Include/eps/eps.h
libs/drivers/eps/Include/eps/hk.hpp
libs/drivers/eps/eps.cpp
libs/drivers/eps/hk.cpp
libs/drivers/gyro/Include/gyro/telemetry.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/telecommunication/include/telecommunication/downlink.h
libs/telemetry/CMakeLists.txt
libs/telemetry/Include/telemetry/ErrorCounters.hpp
libs/telemetry/Include/telemetry/fwd.hpp
libs/telemetry/eps/CMakeLists.txt
libs/telemetry/eps/Include/telemetry/collect_eps.hpp
libs/telemetry/eps/collect_eps.cpp
src/CMakeLists.txt
src/commands/eps.cpp
src/main.cpp
src/mission.h
unit_tests/base/CMakeLists.txt
unit_tests/base/Include/mock/eps.hpp
unit_tests/base/mock/mock.cpp
unit_tests/drivers/CMakeLists.txt
unit_tests/drivers/Comm/DownlinkFrameTest.cpp
unit_tests/drivers/EPS/EpsTelemetryTest.cpp
unit_tests/properties/EPS/EPSDriverTest.cpp
unit_tests/state/CMakeLists.txt
unit_tests/state/telemetry/EpsTelemetryAcquisitionTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/173)

Extend telemetry acquisition with eps state.

---

integration_tests/devices/comm.py
integration_tests/tests/test_comm_support.py
libs/telecommunication/downlink.cpp
unit_tests/base/Include/mock/comm.hpp
unit_tests/communication/Telecommands/EnterIdleStateTelecommandTest.cpp
unit_tests/communication/Telecommands/RemoveFileTelecommandTest.cpp
unit_tests/drivers/Comm/DownlinkFrameTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/176)

Fix downlink frame bit ordering

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
libs/error_counter/Include/error_counter/error_counter.hpp
libs/error_counter/error_counter.cpp
unit_tests/drivers/Comm/CommTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/167)

Implemented error counters for Comm

---

libs/drivers/leuart/Include/leuart/line_io.h
libs/drivers/leuart/leuart.cpp
libs/drivers/uart/Include/uart/uart.h
libs/drivers/uart/uart.cpp
libs/terminal/include/terminal/terminal.h
libs/terminal/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/183)

Moved prompt handling to inside uart driver

---

libs/mission/Include/mission/main.hpp
libs/mission/telemetry/Include/mission/telemetry.hpp
libs/mission/telemetry/telemetry.cpp
src/main.cpp
src/obc.cpp
unit_tests/mission/MissionPlan/MissionLoopTest.cpp
unit_tests/mission/MissionPlan/TelemetryTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/175)

[telemetry] Query telemetry once every 30s and save it once every 5 minutes.

---

libs/drivers/rtc/CMakeLists.txt
libs/drivers/rtc/Include/rtc/rtc.hpp
libs/drivers/rtc/rtc.cpp
libs/obc/hardware/hardware.cpp
src/checks/error_counters.cpp
unit_tests/drivers/CMakeLists.txt
unit_tests/drivers/RTC/RTCTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/179)

Error counter for RTC driver

---

libs/experiments/Include/experiments/experiments.h
libs/telemetry/CMakeLists.txt
libs/telemetry/ExperimentTelemetry.cpp
libs/telemetry/Include/telemetry/ErrorCounters.hpp
libs/telemetry/Include/telemetry/Experiments.hpp
libs/telemetry/Include/telemetry/SystemStartup.hpp
libs/telemetry/Include/telemetry/fwd.hpp
libs/telemetry/Include/telemetry/state.hpp
libs/telemetry/experiments/CMakeLists.txt
libs/telemetry/experiments/Include/telemetry/collect_exp.hpp
libs/telemetry/experiments/collect_exp.cpp
src/CMakeLists.txt
src/main.cpp
src/mission.h
unit_tests/state/CMakeLists.txt
unit_tests/state/telemetry/ExperimentTelemetryTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/187)

Extend telemetry acquisition with experiment state.

---

libs/drivers/n25q/CMakeLists.txt
libs/drivers/n25q/Include/n25q/n25q.h
libs/drivers/n25q/n25q.cpp
libs/obc/storage/Include/obc/storage.h
libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h
libs/obc/storage/n25q_flash/n25q.cpp
src/checks/error_counters.cpp
src/commands/external_flash.cpp
src/obc.cpp
unit_tests/drivers/N25Q/N25QTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/180)

Error counters for N25Q flash

---

libs/drivers/imtq/CMakeLists.txt
libs/drivers/imtq/Include/imtq/imtq.h
libs/drivers/imtq/imtq.cpp
libs/obc/hardware/hardware.cpp
src/checks/error_counters.cpp
unit_tests/drivers/imtq/imtqHighLevelTest.cpp
unit_tests/drivers/imtq/imtqTest.cpp
unit_tests/properties/imtq/imtqTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/178)

Error counters for IMTQ

---

boot/CMakeLists.txt
boot/error_counter.cpp
boot/error_counter.hpp
boot/main.cpp
boot/main.hpp
libs/drivers/fm25w/CMakeLists.txt
libs/drivers/fm25w/Include/fm25w/fm25w.hpp
libs/drivers/fm25w/fm25w.cpp
libs/error_counter/Include/error_counter/error_counter.hpp
libs/obc/hardware/Include/obc/PersistentStorageAccess.hpp
libs/obc/hardware/PersistentStorageAccess.cpp
libs/obc/hardware/hardware.cpp
src/checks/error_counters.cpp
unit_tests/drivers/FM25W/RedundantFM25WDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/189)

Error counter for RedundantFM25WDriver

---

boot/boot.cpp
boot/commands/settings.cpp
integration_tests/obc/boot_settings.py
integration_tests/obc/obc.py
integration_tests/response_frames/frame_decoder.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/boot_settings.py
integration_tests/telecommand/comm.py
integration_tests/tests/test_telecommands_boot_settings.py
libs/boot_settings/Include/boot/fwd.hpp
libs/boot_settings/Include/boot/settings.hpp
libs/boot_settings/settings.cpp
libs/drivers/comm/comm.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/boot_settings.hpp
libs/obc/communication/telecommands/boot_settings.cpp
src/CMakeLists.txt
src/commands/boot_settings.cpp
src/commands/commands.h
src/obc.cpp
src/terminal.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/SetBootSlotsTelecommandTest.cpp
unit_tests/others/BootSettings/BootSettingsTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/181)

Telecommand for setting boot slots

---

libs/drivers/mcu_temp/Include/temp/efm.hpp
libs/drivers/mcu_temp/Include/temp/mcu.hpp
libs/drivers/mcu_temp/efm.cpp
libs/telemetry/CMakeLists.txt
libs/telemetry/Include/telemetry/McuTemperature.hpp
libs/telemetry/Include/telemetry/fwd.hpp
libs/telemetry/Include/telemetry/state.hpp
libs/telemetry/McuTemperature.cpp
libs/telemetry/temp/CMakeLists.txt
libs/telemetry/temp/Include/telemetry/collect_temp.hpp
libs/telemetry/temp/collect_temp.cpp
src/CMakeLists.txt
src/main.cpp
src/mission.h
unit_tests/state/CMakeLists.txt
unit_tests/state/telemetry/McuTemperatureTest.cpp

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/191)

Extend telemetry acquisition with current mcu temperature.

---

boot/CMakeLists.txt
boot/commands/check.cpp
boot/commands/commands.hpp
boot/comms.cpp
integration_tests/tools/upload.py
libs/drivers/program_flash/Include/program_flash/boot_table.hpp
libs/drivers/program_flash/boot_table.cpp

Adds `Health check` command to bootloader that verifies:
* Selected boot slots
* Program copies
* Bootloader copies
* Bootloader in MCU
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/192)

Bootloader command: check settings

---

integration_tests/devices/eps.py
libs/drivers/eps/Include/eps/hk.hpp
libs/drivers/eps/eps.cpp
unit_tests/drivers/EPS/EPSDriverTest.cpp
unit_tests/properties/EPS/EPSDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/201)

EPS: remove error code as first byte

---

libs/drivers/uart/Include/uart/uart.h
libs/drivers/uart/uart.cpp
libs/obc/hardware/hardware.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/205)

Support backspace in terminal

---

boot/CMakeLists.txt
boot/dummy_os.cpp
libs/boot_settings/Include/boot/fwd.hpp
libs/boot_settings/Include/boot/settings.hpp
libs/boot_settings/settings.cpp
libs/obc/communication/telecommands/boot_settings.cpp
libs/obc/scrubbing/Include/obc/scrubbing.hpp
libs/obc/scrubbing/scrubbing.cpp
libs/scrubber/CMakeLists.txt
libs/scrubber/Include/scrubber/boot_settings.hpp
libs/scrubber/boot_settings.cpp
src/obc.cpp
src/obc.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/203)

Boot settings scrubber

---

integration_tests/system/system.py
integration_tests/tests/base.py
integration_tests/tests/test_antenna.py
integration_tests/tests/test_antenna_deployment.py
integration_tests/tests/test_beacon.py
integration_tests/tests/test_comm.py
integration_tests/tests/test_eps.py
integration_tests/tests/test_eps_restarts.py
integration_tests/tests/test_experiment_detumbling.py
integration_tests/tests/test_experiments.py
integration_tests/tests/test_fs.py
integration_tests/tests/test_gyro.py
integration_tests/tests/test_i2c.py
integration_tests/tests/test_imtq.py
integration_tests/tests/test_sail.py
integration_tests/tests/test_telecommands_antenna.py
integration_tests/tests/test_telecommands_boot_settings.py
integration_tests/tests/test_telecommands_comm.py
integration_tests/tests/test_telecommands_experiments.py
integration_tests/tests/test_telecommands_fs.py
integration_tests/tests/test_time.py
integration_tests/tests/test_tmr.py
integration_tests/tests/test_upload_program.py
integration_tests/tests/test_watchdog.py

Small improvment that allows run whole Python test suite in single restart
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/207)

Ability to run test suite in single restart

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/power.py
integration_tests/tests/test_telecommands_power.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/power.hpp
libs/obc/communication/telecommands/power.cpp
libs/power/Include/power/fwd.hpp
src/obc.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/PowerCycleTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/212)

Power cycle telecommand

---

libs/obc/state/ObcState.cpp
libs/state/Include/state/LockablePersistentState.hpp
unit_tests/properties/MissionPlan/MissionTestHelpers.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/215)

Fixed infinite lock and semaphore leak on Persistent State.

---

integration_tests/tests/test_dma_stress.py
integration_tests/tests/test_x.py
libs/drivers/n25q/Include/n25q/n25q.h
libs/drivers/n25q/n25q.cpp
libs/drivers/n25q/redundant_n25q.cpp
libs/drivers/spi/Include/spi/efm.h
libs/drivers/spi/Include/spi/spi.h
libs/drivers/spi/efm.cpp
libs/drivers/standalone/spi/Include/standalone/spi/spi.hpp
libs/drivers/standalone/spi/spi.cpp
libs/obc/hardware/hardware.cpp
platforms/mcu/EngModel/Include/mcu/io_map.h
test/flash/CMakeLists.txt
test/flash/fault_handlers.cpp
test/flash/main.cpp
unit_tests/base/Include/SPI/SPIMock.h
unit_tests/drivers/FM25W/FM25WDriverTest.cpp
unit_tests/drivers/N25Q/N25QTest.cpp
unit_tests/drivers/N25Q/RedundantN25QTest.cpp
unit_tests/drivers/SPI/SPIDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/218)

Stranger things: DMA transfers hanging

---

integration_tests/ipython_profile/startup/02-obc.py
integration_tests/system/system.py
integration_tests/tests/base.py
src/commands/time.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/219)

Fix race condition between OBC start and I2C mock start

---

integration_tests/devices/eps.py
integration_tests/emulator/beacon_parser/error_counting_telementry.py
libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/eps/Include/eps/eps.h
libs/drivers/imtq/Include/imtq/imtq.h
libs/drivers/n25q/Include/n25q/n25q.h
libs/drivers/n25q/redundant_n25q.cpp
libs/drivers/rtc/Include/rtc/rtc.hpp
libs/error_counter/Include/error_counter/error_counter.hpp
libs/obc/storage/n25q_flash/Include/obc/storage/n25q.h
libs/obc/storage/n25q_flash/n25q.cpp
src/checks/error_counters.cpp
unit_tests/drivers/Comm/CommTest.cpp
unit_tests/drivers/N25Q/RedundantN25QTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/216)

N25q tmr error counters

---

integration_tests/emulator/beacon_parser/error_counting_telemetry.py
integration_tests/emulator/beacon_parser/full_beacon_parser.py
libs/drivers/fm25w/Include/fm25w/fm25w.hpp
libs/drivers/payload/CMakeLists.txt
libs/drivers/payload/Include/payload/payload.h
libs/drivers/payload/payload.cpp
libs/obc/hardware/hardware.cpp
src/checks/error_counters.cpp
unit_tests/drivers/payload/PayloadHardwareDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/223)

Payload errorcounters

---

libs/time/timer.cpp
src/CMakeLists.txt
src/blink.cpp
src/blink.hpp
src/main.cpp
unit_tests/mission/MissionPlan/TimeTaskTest.cpp
unit_tests/others/time/SmartWait.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/227)

Blinking time indicator

---

Jenkinsfile
safe_mode/CMakeLists.txt
safe_mode/dummy_os.cpp
safe_mode/main.cpp
safe_mode/safe_mode.cpp
safe_mode/safe_mode.hpp
safe_mode/steps/erase_n25q/step.cpp
safe_mode/steps/erase_n25q/step.hpp
utils/functions.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/226)

Safe mode: erase N25Q flashes

---

libs/adcs/experimental/ExperimentalDetumbling.cpp
unit_tests/others/adcs/experimental/ExperimentalDetumblingTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/229)

Fixed usage of wrong command in MTM

---

integration_tests/obc/error_counters.py
integration_tests/response_frames/__init__.py
integration_tests/response_frames/fdir.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/fdir.py
integration_tests/tests/test_telecommands_fdir.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/fdir.hpp
libs/obc/communication/telecommands/fdir.cpp
libs/telecommunication/include/telecommunication/downlink.h
src/obc.cpp
unit_tests/base/Include/mock/error_counter.hpp
unit_tests/base/mock/error_counter.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/GetErrorCountersConfigTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/231)

Telecommand: get error counters config

---

integration_tests/devices/comm.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/235)

Catching and logging exception regarding full queue

---

libs/base/Include/base/writer.h
libs/base/writer.cpp
libs/drivers/rtc/Include/rtc/rtc.hpp
libs/drivers/rtc/rtc.cpp
libs/obc/hardware/hardware.cpp
src/commands/rtc.cpp
src/main.cpp
unit_tests/base/Include/mock/RtcMock.hpp
unit_tests/drivers/RTC/RTCTest.cpp
unit_tests/others/base/WriterTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/233)

Set RTC time if not correct

---

integration_tests/tools/just_mocks.py
integration_tests/tools/obc_term.py

* IPython-based OBC terminal
* Just mocks: log transmitted frames to file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/237)

Log COMM frame and OBC PyTerm

---

doxyfile
libs/adcs/experimental/CMakeLists.txt
libs/adcs/experimental/Include/adcs/InterfaceTypes.hpp
libs/adcs/experimental/Include/adcs/SunPointing.hpp
libs/adcs/experimental/SunPointing.cpp
libs/external/bspLib/Include/bsp/bsp_can.h
unit_tests/others/CMakeLists.txt
unit_tests/others/adcs/experimental/CMakeLists.txt
unit_tests/others/adcs/experimental/DetumblingComputationsTest.cpp
unit_tests/others/adcs/experimental/Include/adcs/dataFileTools.hpp
unit_tests/others/adcs/experimental/adcsDetumblingUtConfig.h.in
unit_tests/others/adcs/experimental/adcsUtConfig.h.in
unit_tests/others/adcs/experimental/sunPointingTest.cpp

ICD proposal for SunPointing. 
Reflects algorithm actions and interfaces for the rest of OBC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/185)

SunPointing ICD

---

libs/mission/antenna/Include/mission/antenna_state.h
libs/mission/antenna/antenna.cpp
unit_tests/mission/MissionPlan/antenna/AntennaMissionStateTest.cpp
unit_tests/mission/MissionPlan/antenna/DeployAntennasTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/238)

Query antenna controller in mission update only if it is powered on

---

libs/power/power_eps/Include/power_eps/power_eps.h
libs/power/power_eps/power_eps.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/239)

Interleave EPS controllers on power cycle

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/downlink_frame_factory.py
integration_tests/response_frames/period_message.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/periodic_message.py
libs/mission/comm/CMakeLists.txt
libs/mission/comm/Include/mission/comm.hpp
libs/mission/comm/comm.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp
libs/obc/communication/telecommands/periodic_message.cpp
libs/state/CMakeLists.txt
libs/state/Include/state/comm/MessageState.hpp
libs/state/Include/state/fwd.hpp
libs/state/Include/state/struct.h
libs/state/comm.cpp
libs/telecommunication/include/telecommunication/downlink.h
src/main.cpp
src/mission.h
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/SetPeriodicMessageTelecommandTest.cpp
unit_tests/mission/CMakeLists.txt
unit_tests/mission/MissionPlan/SendMessageTest.cpp
unit_tests/state/CMakeLists.txt
unit_tests/state/state/MessageStateTest.cpp

You will be assimilated
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/230)

Message: Resistance is futile

---

integration_tests/devices/eps.py
integration_tests/emulator/beacon_parser/eps_controller_a_telemetry_parser.py
integration_tests/emulator/beacon_parser/eps_controller_b_telemetry_parser.py
integration_tests/tests/test_eps.py
libs/drivers/eps/Include/eps/hk.hpp
libs/drivers/eps/eps.cpp
libs/drivers/eps/hk.cpp
libs/telemetry/Include/telemetry/state.hpp
src/commands/eps.cpp
unit_tests/drivers/EPS/EpsTelemetryTest.cpp
unit_tests/properties/EPS/EPSDriverTest.cpp

* Update eps driver to match recent firmware changes:
* [CtrlA] Remove DISTR.TEMP
* [CtrlA] Rename ERR -> SAFETY_CTR
* [CtrlA] Add SUPP_TEMP after TEMP, 10 bits
* [CtrlB] Rename ERR -> SAFETY_CTR
* [CtrlB] Add SUPP_TEMP after TEMP, 10 bits
* Update eps telemetry to match driver changes,
* Update eps integration tests,
* Update eps telemetry element parser
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/240)

[telemetry][eps] Eps driver & telemetrt update.

---

integration_tests/telecommand/base.py
integration_tests/telecommand/experiments.py
integration_tests/tests/test_experiment_detumbling.py
integration_tests/tests/test_telecommands_experiments.py
libs/experiments/Include/experiments/experiments.h
libs/experiments/adcs/Include/experiment/adcs/adcs.hpp
libs/experiments/fs/Include/fs/ExperimentFile.hpp
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/experiments.hpp
libs/obc/communication/telecommands/experiments.cpp
libs/obc/experiments/Include/obc/experiments.hpp
libs/obc/experiments/experiments.cpp
src/commands/mission.cpp
unit_tests/base/Include/mock/experiment.hpp
unit_tests/base/mock/mock.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/AbortExperimentTelecommandTest.cpp
unit_tests/communication/Telecommands/PerformDetumblingExperimentTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/241)

Response for experiments TCs

---

integration_tests/telecommand/time.py
integration_tests/tests/test_telecommands_time.py
libs/mission/time/Include/mission/time.hpp
libs/mission/time/time.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/time.hpp
libs/obc/communication/telecommands/time.cpp
libs/time/include/time/ICurrentTime.hpp
libs/time/include/time/timer.h
src/obc.cpp
unit_tests/base/CMakeLists.txt
unit_tests/base/Include/mock/time.hpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/210)

[TeleComm] Added SetTime telecommand

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/i2c.py
integration_tests/tests/test_telecommands_rawi2c.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/i2c.hpp
libs/obc/communication/telecommands/i2c.cpp
src/obc.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/RawI2CTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/224)

[TeleComm] Added raw I2C telecommand

---

libs/base/Include/line_io.h
libs/drivers/camera/CMakeLists.txt
libs/drivers/camera/Include/camera/camera.h
libs/drivers/camera/Include/camera/camera_low_level.h
libs/drivers/camera/camera.cpp
libs/drivers/camera/camera_low_level.cpp
libs/drivers/uart/Include/uart/uart.hpp
libs/terminal/include/terminal/terminal.h
libs/terminal/terminal.cpp
src/checks/error_counters.cpp
src/obc.cpp
src/obc.h
unit_tests/base/Include/mock/LineIOMock.hpp
unit_tests/base/Include/utils.hpp
unit_tests/base/mock/mock.cpp
unit_tests/drivers/CMakeLists.txt
unit_tests/drivers/camera/CameraTest.cpp
unit_tests/drivers/camera/CameraTestCommands.hpp
unit_tests/drivers/camera/LowLevelCameraTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/247)

Ucam II unit tests

---

integration_tests/devices/comm.py
integration_tests/devices/imtq.py
integration_tests/response_frames/beacon_factory.py
integration_tests/tools/comm_client.py
integration_tests/tools/just_mocks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/246)

COMM client

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/suns.py
integration_tests/tests/test_telecommands_suns.py
libs/experiments/suns/Include/experiment/suns/suns.hpp
libs/experiments/suns/suns.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/suns.hpp
libs/obc/communication/telecommands/Include/obc/telecommands/time.hpp
libs/obc/communication/telecommands/suns.cpp
src/obc.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/GetSunSDataSetsTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/249)

SunS Telecommand

---

integration_tests/experiment_file/__init__.py
integration_tests/experiment_file/base.py
integration_tests/experiment_file/sail.py
test/generate_exp_data/CMakeLists.txt
test/generate_exp_data/main.cpp
test/generate_exp_data/sail_data.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/256)

Sail parser

---

integration_tests/devices/__init__.py
integration_tests/devices/camera.py
integration_tests/obc/camera.py
integration_tests/obc/file_system.py
integration_tests/system/system.py
integration_tests/tests/test_camera.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/253)

Added camera related commands to ease cam operations

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/Include/comm/comm.hpp
libs/drivers/comm/comm.cpp
libs/mission/comm/CMakeLists.txt
libs/mission/comm/Include/mission/comm_wdog.hpp
libs/mission/comm/comm_wdog.cpp
src/main.cpp
src/mission.h
unit_tests/base/Include/mock/comm.hpp
unit_tests/base/mock/comm.cpp
unit_tests/mission/CMakeLists.txt
unit_tests/mission/MissionPlan/comm/CommWdogTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/254)

[mission][comm] Synchronize mission with comm hardware polling task.

---

libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
unit_tests/drivers/CMakeLists.txt
unit_tests/drivers/Comm/CommThreadsafeTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/255)

Made CommObject thread-safe

---

integration_tests/devices/__init__.py
integration_tests/devices/camera.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/photo.py
integration_tests/tests/test_telecommands_photo.py
libs/base/Include/base/reader.h
libs/base/reader.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp
libs/obc/communication/telecommands/experiments.cpp
libs/obc/communication/telecommands/photo.cpp
src/obc.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/PhotoCommandTest.cpp
unit_tests/others/base/ReaderTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/257)

[Telecommand] Take photo

---

libs/experiments/radfet/Include/experiment/radfet/radfet.hpp
libs/experiments/radfet/radfet.cpp
unit_tests/mission/Experiments/RadFET/RadFETExperimentTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/262)

Fix RadFET experiment setup

---

integration_tests/emulator/beacon_parser/experiment_telemetry_parser.py
integration_tests/obc/experiments.py
libs/experiments/adcs/Include/experiment/adcs/adcs.hpp
libs/experiments/fibo/Include/experiment/fibo/fibo.h
libs/experiments/flash/Include/experiment/flash/flash.hpp
libs/experiments/leop/Include/experiment/leop/leop.hpp
libs/experiments/radfet/Include/experiment/radfet/radfet.hpp
libs/experiments/suns/Include/experiment/suns/suns.hpp
libs/telemetry/Include/telemetry/Experiments.hpp
libs/telemetry/Include/telemetry/state.hpp
unit_tests/state/telemetry/ExperimentTelemetryTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/261)

Update experiment codes, changed telemetry to use 4 bits for experiment code

---

integration_tests/camera_mock.py
integration_tests/scripts/photo_test.py
integration_tests/tools/camera_mock.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/264)

Camera mock

---

integration_tests/telecommand/photo.py
integration_tests/tests/test_telecommands_photo.py
libs/obc/communication/telecommands/photo.cpp
unit_tests/communication/Telecommands/PhotoCommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/268)

[telecommand][take_photo] Add delay parameter to take photo command.

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/photo.py
integration_tests/tests/test_telecommands_photo.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/photo.hpp
libs/obc/communication/telecommands/photo.cpp
libs/photo/Include/photo/fwd.hpp
libs/photo/Include/photo/photo_service.hpp
libs/photo/photo_service.cpp
unit_tests/others/photos/PhotoServiceTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/272)

[TC][purge_photo] Add command to reset state of the photo service.

---

integration_tests/emulator/beacon_parser/eps_controller_a_telemetry_parser.py
libs/base/Include/utils.h
libs/drivers/eps/Include/eps/hk.hpp
libs/telemetry/Include/telemetry/state.hpp
unit_tests/drivers/EPS/EpsTelemetryTest.cpp

Temperatures in battery pack in controller A telemetry are now 13 bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/269)

[eps][telemetry] Eps telemetry update.

---

integration_tests/devices/imtq.py
integration_tests/obc/adcs.py
integration_tests/obc/imtq.py
integration_tests/obc/obc.py
integration_tests/scripts/boot_runlevel1.py
integration_tests/scripts/detumbling_crossvalidation.py
libs/adcs/AdcsCoordinator.cpp
libs/obc/adcs/Include/obc/adcs_fwd.hpp
src/CMakeLists.txt
src/commands/adcs.cpp
src/commands/commands.h
src/commands/ping.cpp
src/obc_access.cpp
src/obc_access.hpp
src/terminal.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/277)

Detumbling improvments

---

integration_tests/i2cMock/i2cMock.py
integration_tests/tests/test_experiment_detumbling.py
integration_tests/tests/test_imtq.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/280)

Device Mock version 5

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/periodic_message.py
integration_tests/tests/test_telecommand_send_periodic.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/periodic_message.hpp
libs/obc/communication/telecommands/periodic_message.cpp
libs/state/Include/state/comm/MessageState.hpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/SendPeriodicMessageTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/276)

Telecommand: send periodic message now

---

libs/drivers/payload/Include/payload/commands/base_code.hpp
libs/drivers/payload/Include/payload/payload.h
libs/drivers/payload/payload.cpp
libs/drivers/suns/Include/suns/suns.hpp
libs/drivers/suns/suns.cpp
unit_tests/drivers/payload/PayloadHardwareDriverTest.cpp
unit_tests/drivers/suns/sunsTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/281)

Fixed PLD and Suns interrupt handlers in case of extra glitches on GPIO

---

integration_tests/emulator/beacon_parser/antenna_telemetry_parser.py
integration_tests/emulator/beacon_parser/comm_telemetry_parser.py
integration_tests/emulator/beacon_parser/eps_controller_a_telemetry_parser.py
integration_tests/emulator/beacon_parser/eps_controller_b_telemetry_parser.py
integration_tests/emulator/beacon_parser/error_counting_telemetry.py
integration_tests/emulator/beacon_parser/experiment_telemetry_parser.py
integration_tests/emulator/beacon_parser/file_system_telemetry_parser.py
integration_tests/emulator/beacon_parser/gpio_state_parser.py
integration_tests/emulator/beacon_parser/gyroscope_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_bdot_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_coil_active.py
integration_tests/emulator/beacon_parser/imtq_coils_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_dipole_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_housekeeping_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_magnetometers_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_self_test_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_state_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_temperature_telemetry_parser.py
integration_tests/emulator/beacon_parser/mcu_temperature_parser.py
integration_tests/emulator/beacon_parser/parser.py
integration_tests/emulator/beacon_parser/program_state.py
integration_tests/emulator/beacon_parser/scrubbing_telemetry_parser.py
integration_tests/emulator/beacon_parser/startup_parser.py
integration_tests/emulator/beacon_parser/time_state.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/279)

Beacon in property grid is now ordered according to telemetry

---

integration_tests/tests/test_experiment_leop.py
libs/experiments/leop/Include/experiment/leop/leop.hpp
libs/experiments/leop/leop.cpp
libs/fs/Include/fs/fs.h

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/282)

Made LEOP experiment not overwrite data file after system restart

---

libs/drivers/camera/camera.cpp
unit_tests/drivers/camera/CameraTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/283)

Camera: retrying photo download

---

integration_tests/devices/payload.py
integration_tests/devices/suns.py
integration_tests/emulator/beacon.py
integration_tests/emulator/beacon_parser/parser.py
integration_tests/experiment_file/__init__.py
integration_tests/experiment_file/camera.py
integration_tests/experiment_file/payload.py
integration_tests/experiment_file/photodiodes.py
integration_tests/experiment_file/radfet.py
integration_tests/experiment_file/temps.py
integration_tests/tests/test_experiment_camera.py
integration_tests/tests/test_experiment_payload.py
integration_tests/tests/test_experiment_suns.py
integration_tests/tests/test_telecommands_suns.py
libs/drivers/gyro/GyroscopeTelemetry.cpp
libs/drivers/gyro/Include/gyro/telemetry.hpp
libs/drivers/payload/Include/payload/telemetry.h
libs/drivers/payload/telemetry.cpp
libs/drivers/suns/Include/suns/suns.hpp
libs/drivers/suns/suns.cpp
libs/experiments/fs/Include/fs/ExperimentFile.hpp
libs/experiments/leop/leop.cpp
libs/experiments/payload/payload_exp.cpp
libs/experiments/radfet/Include/experiment/radfet/radfet.hpp
libs/experiments/radfet/radfet.cpp
libs/experiments/suns/suns.cpp
test/generate_exp_data/CMakeLists.txt
test/generate_exp_data/main.cpp
test/generate_exp_data/os_stubs.cpp
unit_tests/properties/Experiments/SunSDataPointTest.cpp

And parser enhancements
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/285)

Experiment file cleanup

---

integration_tests/experiment_file/gyro.py
test/generate_exp_data/CMakeLists.txt
test/generate_exp_data/camera_data.cpp
test/generate_exp_data/leop_data.cpp
test/generate_exp_data/main.cpp
test/generate_exp_data/payload_data.cpp
test/generate_exp_data/radfet_data.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/286)

Experiment file generator update

---

libs/drivers/comm/comm.cpp
unit_tests/drivers/Comm/CommTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/287)

Added error counters to Comm driver

---

integration_tests/tools/upload.py
integration_tests/tools/upload_safe_mode.py

Simple check if user during uploadin doesn't try to provide file in incorrect format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/294)

[Firmware upload scripts] Check if provided file is in correct format.

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/sail_experiment.py
integration_tests/tests/test_experiment_sail.py
libs/base/Include/base/delegate.hpp
libs/experiments/fs/ExperimentFile.cpp
libs/experiments/fs/Include/fs/ExperimentFile.hpp
libs/experiments/sail/CMakeLists.txt
libs/experiments/sail/Include/experiment/sail/sail.hpp
libs/experiments/sail/sail.cpp
libs/obc/communication/telecommands/experiments.cpp
libs/obc/experiments/experiments.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/communication/CMakeLists.txt
unit_tests/mission/Experiments/Sail/SailExperimentTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/278)

Added automatic telemetry sending during Sail experiment

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/disable_overheat_submode.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/eps.py
integration_tests/tests/test_telecommands_eps.py
libs/drivers/eps/Include/eps/eps.h
libs/drivers/eps/Include/eps/fwd.hpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/eps.hpp
libs/obc/communication/telecommands/eps.cpp
libs/telecommunication/include/telecommunication/downlink.h
src/obc.cpp
unit_tests/base/Include/mock/eps.hpp
unit_tests/base/mock/mock.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/DisableOverheatSubmodeTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/290)

[TeleComm] Added DisableOverheatSubmode command

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/set_bitrate.py
integration_tests/telecommand/comm.py
integration_tests/tests/test_telecommands_comm.py
libs/drivers/comm/comm.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/comm.hpp
libs/obc/communication/telecommands/comm.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/SetBitrateTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/289)

[TeleComm] Added SetBitrate telecommand

---

integration_tests/telecommand/comm.py
integration_tests/tests/test_telecommands_comm.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/comm.hpp
libs/obc/communication/telecommands/comm.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/ResetTransmitterTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/296)

[Telecommands] Reset Transmitter Telecommand

---

integration_tests/tests/test_telecommands_compile_info.py
libs/drivers/comm/Include/comm/CommDriver.hpp
libs/drivers/comm/comm.cpp
unit_tests/drivers/Comm/CommTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/298)

Detect comm stalling and restart transmitter

---

integration_tests/tests/test_experiment_sail.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/299)

Sail autosend test fix

---

integration_tests/scripts/upload_software.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/304)

PyConsole script for uploading new program

---

libs/external/googletest/CMakeLists.txt
libs/external/rapidcheck/CMakeLists.txt
platforms/mcu/EngModel/settings.cmake
platforms/mcu/FlightModel/settings.cmake
src/CMakeLists.txt
unit_tests/common.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/309)

Disable RTTI

---

integration_tests/tests/test_gyro.py
libs/drivers/gyro/driver.cpp
unit_tests/drivers/gyro/gyroTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/307)

Reintialize gyroscope if read failed

---

integration_tests/obc/obc.py
integration_tests/obc/obc_rtos.py
libs/photo/Include/photo/photo_service.hpp
platforms/mcu/DevBoard/Include/FreeRTOSConfig.h
platforms/mcu/EngModel/Include/FreeRTOSConfig.h
platforms/mcu/FlightModel/Include/FreeRTOSConfig.h

Fixed issue when long running Experiment (for example Copy Boot Slots) causes transfer errors on N25Q and FRAM.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/311)

Raised priority of System task and reduced priority of Photo task.

---

integration_tests/emulator/comm.py
integration_tests/ipython_profile/startup/03-emulator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/313)

Fix beacon in emulator

---

Jenkinsfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/316)

Changed security code for CI builds

---

boot/commands/boot_table.cpp
boot/commands/booting.cpp
boot/commands/check.cpp
boot/commands/settings.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/319)

[boot] Fix boot loader hang in health check on boot slot CRC mismatch.

---

safe_mode/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/323)

Restore boot slots as last step

---

integration_tests/tests/test_experiments.py
integration_tests/tests/test_fs.py
integration_tests/tests/test_telecommands_fs.py
integration_tests/tests/test_tmr.py
libs/experiments/fibo/fibo.cpp
src/obc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/320)

[obc] Do not create "a" directory on startup.

---

src/obc.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/325)

Disable power cycle trigger for all devices except COM & EPS.

---

integration_tests/tests/test_startup.py
libs/obc/hardware/Include/obc/hardware.h
libs/obc/hardware/hardware.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/324)

[obc][eps] Reset lcls on obc startup.

---

libs/drivers/antenna/miniport.cpp
libs/drivers/i2c/Include/i2c/efm.h
libs/drivers/i2c/Include/i2c/i2c.h
libs/drivers/i2c/efm.cpp
libs/obc/hardware/hardware.cpp
unit_tests/drivers/payload/PayloadHardwareDriverTest.cpp

- Added SDA line in checking for latch-up
- Enabled Mission Loop resuming in case of permamently latched bus SDA.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/329)

Fix SDA latchup

---

integration_tests/tests/test_experiment_leop.py
libs/experiments/leop/Include/experiment/leop/leop.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/333)

Extend LEOP experiment to T+4h

---

libs/mission/time/Include/mission/time.hpp
libs/mission/time/time.cpp
unit_tests/mission/MissionPlan/TimeTaskTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/326)

Time stops (like in Groundhog Day) when RTC dies

---

integration_tests/devices/imtq.py
integration_tests/tests/test_adcs.py
integration_tests/tests/test_experiment_detumbling.py
integration_tests/tests/test_imtq.py
integration_tests/tools/decode_telemetry_file.py
libs/adcs/builtin/BuiltinDetumbling.cpp
libs/drivers/imtq/imtq.cpp
unit_tests/drivers/imtq/imtqHighLevelTest.cpp
unit_tests/others/adcs/builtin/BuiltinDetumblingTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/330)

Perform self test before enabling builtin detumbling

---

integration_tests/devices/eps.py
libs/drivers/eps/Include/eps/fwd.hpp
libs/drivers/eps/eps.cpp
unit_tests/drivers/EPS/EPSDriverTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/337)

Ignoring EPS error code

---

integration_tests/emulator/beacon_parser/error_counting_telemetry.py
libs/drivers/antenna/CMakeLists.txt
libs/drivers/antenna/Include/antenna/driver.h
libs/drivers/antenna/Include/antenna/miniport.h
libs/drivers/antenna/antenna.cpp
libs/drivers/antenna/miniport.cpp
libs/error_counter/Include/error_counter/error_counter.hpp
libs/error_counter/error_counter.cpp
libs/obc/hardware/hardware.cpp
libs/telemetry/Include/telemetry/ErrorCounters.hpp
libs/telemetry/Include/telemetry/state.hpp
src/checks/error_counters.cpp
unit_tests/base/Include/mock/MiniportMock.hpp
unit_tests/communication/Telecommands/GetErrorCountersConfigTelecommandTest.cpp
unit_tests/drivers/antenna/antenna.cpp
unit_tests/drivers/antenna/miniport.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/336)

ANTs error counters

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/stop_sail_deployment.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/sail.py
integration_tests/tests/test_telecommands_sail.py
libs/mission/sail/Include/mission/sail.hpp
libs/mission/sail/sail.cpp
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/sail.hpp
libs/obc/communication/telecommands/sail.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/StopSailDeploymentTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/301)

Telecomm stop sail

---

integration_tests/emulator/beacon_parser/antenna_telemetry_parser.py
integration_tests/tools/decode_telemetry_file.py

- antenna channel order
- file parser size fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/340)

Beacon telemetry fixes

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/memory.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/memory.py
libs/obc/communication/Include/obc/communication.h
libs/obc/communication/communication.cpp
libs/obc/communication/telecommands/CMakeLists.txt
libs/obc/communication/telecommands/Include/obc/telecommands/memory.hpp
libs/obc/communication/telecommands/memory.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/base/Include/mock/comm.hpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/PowerCycleTelecommandTest.cpp
unit_tests/communication/Telecommands/ReadMemoryTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/332)

Telecommand for reading memory space

---

libs/obc/communication/telecommands/adcs.cpp
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/AdcsTelecommandsTest.cpp

* Also unit tests for adcs telecommands
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/343)

Fix for SetAdcsMode

---

integration_tests/tests/test_experiment_leop.py
libs/experiments/leop/leop.cpp
libs/fs/Include/fs/fs.h
libs/fs/Include/fs/yaffs.h
libs/fs/yaffs.cpp
test/generate_exp_data/main.cpp
unit_tests/base/Include/mock/FsMock.hpp
unit_tests/mission/Experiments/LEOP/LEOPExperimentTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/344)

Added telemetry file copy at LEOP experiment end

---

integration_tests/emulator/beacon_parser/comm_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_bdot_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_dipole_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_housekeeping_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_magnetometers_telemetry_parser.py

[second PR because jenkins didn't like previous branch name]
- mW to dBm change for RF power, fixed scaling
- imtq units to microteslas and current to miliamps
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/342)

imtq and comm parser minor changes

---

boot/CMakeLists.txt
boot/commands/commands.hpp
boot/commands/settings.cpp
boot/comms.cpp
safe_mode/CMakeLists.txt
safe_mode/main.cpp

Add build information to safe mode & boot  loader.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/339)

Build info

---

libs/obc/communication/telecommands/photo.cpp

Fix bug as described in https://team.pw-sat.pl/w/ncr/ncr40/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/347)

Fixed file save path for photos telecommand

---

integration_tests/response_frames/common.py
integration_tests/tests/test_telecommands_time.py
libs/obc/communication/telecommands/time.cpp
unit_tests/communication/Telecommands/SetTimeTelecommandTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/352)

Set time telecommand works when RTC is down

---

integration_tests/experiment_file/__init__.py
integration_tests/experiment_file/temps.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/354)

[NCR #043] Fixed SADS experiment file parsing issue.

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/common.py
integration_tests/response_frames/file_system.py
integration_tests/scripts/camera_emu.py
integration_tests/telecommand/sail.py
integration_tests/tests/test_sail.py
integration_tests/tests/test_telecommands_sail.py
libs/experiments/sail/sail.cpp
libs/mission/sail/Include/mission/sail.hpp
libs/mission/sail/sail.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/sail.hpp
libs/obc/communication/telecommands/photo.cpp
libs/obc/communication/telecommands/sail.cpp
libs/power/Include/power/power.h
libs/power/power_eps/Include/power_eps/power_eps.h
libs/power/power_eps/power_eps.cpp
src/commands/sail.cpp
test/generate_persistent_state/CMakeLists.txt
test/generate_persistent_state/main.cpp
test/generate_persistent_state/os_stubs.cpp
unit_tests/base/Include/mock/OpenSailMock.hpp
unit_tests/base/Include/mock/power.hpp
unit_tests/communication/Telecommands/OpenSailTelecommandTest.cpp
unit_tests/mission/MissionPlan/sail/OpenSailTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/351)

Disable EPS overheat submode when opening sail

---

libs/photo/photo_service.cpp
unit_tests/others/photos/PhotoServiceTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/358)

[NCR #42] Disabling cameras after purging photo service queue

---

libs/fs/Include/fs/fs.h
libs/fs/Include/fs/yaffs.h
libs/fs/yaffs.cpp
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/file_system.cpp
test/generate_exp_data/main.cpp
unit_tests/base/Include/mock/FsMock.hpp
unit_tests/others/FileSystem/FileSystemTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/360)

[NCR #047] Fixed HF when downloading a folder instead of a file.

---

boot/main.cpp
src/main.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/363)

Initialize all unused pins

---

libs/obc/communication/telecommands/photo.cpp
libs/photo/photo_service.cpp
unit_tests/base/Include/mock/comm.hpp
unit_tests/base/mock/comm.cpp
unit_tests/communication/Telecommands/PhotoCommandTest.cpp
unit_tests/others/photos/PhotoServiceTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/364)

[ncr #51] Fix sail experiment/purge photo service telecommand conflict.

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/comm.py
libs/obc/communication/telecommands/Include/obc/telecommands/file_system.hpp
libs/obc/communication/telecommands/comm.cpp
libs/obc/communication/telecommands/file_system.cpp
libs/obc/communication/telecommands/program_upload.cpp
libs/telecommunication/include/telecommunication/downlink.h
unit_tests/communication/CMakeLists.txt
unit_tests/communication/Telecommands/DownloadFileTelecommandTest.cpp
unit_tests/communication/Telecommands/SendBeaconTelecommandTest.cpp
unit_tests/communication/Telecommands/UploadProgramTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/365)

No response frames

---

integration_tests/telecommand/adcs.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/366)

Fixed payload value when sending Disable ADCS command

---

libs/obc/communication/telecommands/sail.cpp
libs/state/Include/state/struct.h
libs/state/state.cpp
unit_tests/communication/Telecommands/StopSailDeploymentTelecommandTest.cpp
unit_tests/mission/MissionPlan/MissionPlanTest.cpp
unit_tests/mission/MissionPlan/sads/DeploySolarArrayTest.cpp
unit_tests/mission/MissionPlan/sail/OpenSailTest.cpp

Update stop sail deployment telecommand to be able to unconditionally and at any point in time stop the sail deployment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/368)

[NCR #49] Update StopSailDeployment telecommand

---

libs/adcs/experimental/DetumblingComputations.cpp
libs/adcs/experimental/ExperimentalDetumbling.cpp
libs/adcs/experimental/Include/adcs/DetumblingComputations.hpp
libs/adcs/experimental/Include/adcs/ExperimentalDetumbling.hpp
libs/adcs/experimental/Include/adcs/InterfaceTypes.hpp
test/generate_persistent_state/main.cpp
unit_tests/others/adcs/experimental/DetumblingComputationsTest.cpp
unit_tests/others/adcs/experimental/ExperimentalDetumblingTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/362)

[NCR #024] Fixed overflow in detumbling calculations

---

libs/photo/photo_service.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/371)

[photo] Extend photo service diagnostics.

---

integration_tests/response_frames/period_message.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/370)

[NCR #052] Added frame decoders for SetPeriodic.

---

integration_tests/response_frames/__init__.py
integration_tests/scripts/current_persistent_state.py
libs/obc/communication/telecommands/state.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/373)

Fixed GetPersistentState telecommand

---

integration_tests/tools/upload.py
integration_tests/tools/upload_safe_mode.py

Option useful for upload via umbilical
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/375)

Option 'nowait' for bootloader added to upload tools

---

libs/experiments/sail/sail.cpp
unit_tests/mission/Experiments/Sail/SailExperimentTest.cpp

Give the photo service some time to take & download high resolution photos before stopping the sail experiment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/374)

[sail][experiment] Sail experiment update

---

integration_tests/emulator/beacon_parser/gpio_state_parser.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/378)

The answer for the question wheter sail is deployed is given directly by the GPIO state.

---

integration_tests/response_frames/__init__.py
integration_tests/response_frames/common.py
integration_tests/response_frames/time.py
integration_tests/tests/test_comm.py
integration_tests/tests/test_experiment_camera.py
integration_tests/tests/test_experiment_detumbling.py
integration_tests/tests/test_experiment_payload.py
integration_tests/tests/test_experiment_radfet.py
integration_tests/tests/test_experiment_sads.py
integration_tests/tests/test_experiment_sail.py
integration_tests/tests/test_experiment_suns.py
integration_tests/tests/test_telecommand_send_periodic.py
integration_tests/tests/test_telecommands_adcs.py
integration_tests/tests/test_telecommands_boot_settings.py
integration_tests/tests/test_telecommands_comm.py
integration_tests/tests/test_telecommands_compile_info.py
integration_tests/tests/test_telecommands_eps.py
integration_tests/tests/test_telecommands_fdir.py
integration_tests/tests/test_telecommands_fs.py
integration_tests/tests/test_telecommands_get_persistent_state.py
integration_tests/tests/test_telecommands_photo.py
integration_tests/tests/test_telecommands_power.py
integration_tests/tests/test_telecommands_rawi2c.py
integration_tests/tests/test_telecommands_suns.py
integration_tests/tests/test_telecommands_time.py
integration_tests/tests/test_upload_program.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/377)

Added frame filters to get_frame on tests.

---

integration_tests/experiment_file/photodiodes.py
integration_tests/experiment_file/temps.py

https://team.pw-sat.pl/w/ncr/ncr53
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/376)

Swapped Sockets For Solar Panels On PLD Board fix

---

integration_tests/devices/imtq.py
integration_tests/emulator/beacon_parser/imtq_housekeeping_telemetry_parser.py
integration_tests/emulator/beacon_parser/imtq_temperature_telemetry_parser.py
integration_tests/emulator/beacon_parser/mcu_temperature_parser.py
integration_tests/obc/mcu_temp.py
integration_tests/obc/obc.py
libs/drivers/mcu_temp/Include/temp/efm.hpp
libs/drivers/mcu_temp/Include/temp/mcu.hpp
libs/drivers/mcu_temp/efm.cpp
src/commands/temp.cpp
unit_tests/base/Include/mock/TemperatureReaderMock.hpp

Added possibility to retrieve MCU Temperature calibration coefficients.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/379)

Fixed calculating MCU and IMTQ temperatures.

---

boot/boot.cpp
boot/commands/settings.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/381)

Boot to safe mode when no magic number

---

integration_tests/devices/comm.py
integration_tests/emulator/beacon_parser/mcu_temperature_parser.py
integration_tests/emulator/beacon_parser/startup_parser.py
integration_tests/scripts/download_file.py
integration_tests/telecommand/__init__.py
integration_tests/telecommand/experiments.py
integration_tests/telecommand/fdir.py
integration_tests/telecommand/fs.py
integration_tests/telecommand/ping.py
integration_tests/telecommand/time.py
integration_tests/tests/test_telecommands_fdir.py
integration_tests/tests/test_telecommands_time.py
libs/obc/communication/telecommands/power.cpp

Fixes of minor issues that have been found during last testing session.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/383)

Several minor fixes

---

Jenkinsfile
boot/CMakeLists.txt
integration_tests/tools/crc.py
integration_tests/tools/pad_file.py
jlink/flash.jlink.template
safe_mode/CMakeLists.txt
utils/functions.cmake

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/382)

Safe mode & bootloader padding

---

integration_tests/devices/comm.py
integration_tests/response_frames/file_system.py
integration_tests/telecommand/adcs.py
integration_tests/telecommand/base.py
integration_tests/telecommand/comm.py
integration_tests/telecommand/experiments.py
integration_tests/telecommand/fs.py
integration_tests/telecommand/photo.py

… so that they are readable in console. 
I focused on TCs used in last "40-day mission"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/384)

Added formatting to Telecommands and Resposnses

---

integration_tests/emulator/beacon.py
integration_tests/emulator/comm.py
integration_tests/emulator/comm_zmq_adapter.py
integration_tests/emulator/gui.fbp
integration_tests/emulator/gui.xrc
integration_tests/ipython_profile/startup/03-emulator.py
integration_tests/requirements.txt
integration_tests/tools/just_mocks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/386)

JustMocks/PyConsole <--> ZeroMQ bridge

---

libs/experiments/fs/Include/fs/ExperimentFile.hpp
src/checks/checks.cpp
unit_tests/mission/Experiments/fs/ExperimentFileTest.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/387)

Fixed packet length for ExperimentFile

---

integration_tests/tools/just_mocks.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/388)

Just-Mocks: option do disable ZeroMQ

---

integration_tests/obc/camera.py
integration_tests/obc/flash.py
integration_tests/obc/imtq.py
integration_tests/obc/obc.py
integration_tests/obc/obc_time.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/389)

More terminal commands in python

---

integration_tests/response_frames/__init__.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/390)

[integration_tests] Fix response_frames package initialization/exports.

---

libs/external/eigen/CMakeLists.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/391)

Point eigen lib to PW-Sat2 fork

---

integration_tests/emulator/comm_zmq_adapter.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/392)

Linked Emulator to GnuRadio COM Mock

---

integration_tests/devices/comm.py
integration_tests/devices/comm_beacon.py
integration_tests/emulator/beacon.py
integration_tests/emulator/beacon_parser/experiment_telemetry_parser.py
integration_tests/experiment_type.py
integration_tests/ipython_profile/startup/03-emulator.py
integration_tests/obc/experiments.py
integration_tests/response_frames/__init__.py
integration_tests/response_frames/beacon_factory.py
integration_tests/response_frames/file_system.py
integration_tests/tests/test_telecommands_comm.py
integration_tests/tests/test_telecommands_eps.py
integration_tests/tests/test_telecommands_rawi2c.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/394)

Beacon view

---

integration_tests/telecommand/__init__.py
integration_tests/telecommand/adcs.py
integration_tests/telecommand/antenna.py
integration_tests/telecommand/base.py
integration_tests/telecommand/boot_settings.py
integration_tests/telecommand/comm.py
integration_tests/telecommand/eps.py
integration_tests/telecommand/experiments.py
integration_tests/telecommand/fdir.py
integration_tests/telecommand/fs.py
integration_tests/telecommand/memory.py
integration_tests/telecommand/periodic_message.py
integration_tests/telecommand/photo.py
integration_tests/telecommand/power.py
integration_tests/telecommand/sail.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/395)

Unify correlation_id handling in all telecommands.

---

integration_tests/devices/__init__.py
integration_tests/emulator/beacon_parser/comm_telemetry_parser.py
integration_tests/emulator/beacon_parser/eps_controller_a_telemetry_parser.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/396)

Export BeaconFrame from Python devices package

---

integration_tests/devices/comm_beacon.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/397)

Validate beacon ranges

---

integration_tests/telecommand/experiments.py
integration_tests/telecommand/power.py
integration_tests/telecommand/suns.py
integration_tests/telecommand/time.py

Most importantly update time related telecommands to allow access to unencoded parameters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/399)

Minor telecommand updates

---

integration_tests/emulator/comm_zmq_adapter.py
integration_tests/requirements.txt
integration_tests/tools/just_mocks.py

* adds `uplink_per` and `downlink_per` parameters to `just_mocks` in order to simulate packet error rate.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/401)

PER simulation

---

integration_tests/devices/comm_beacon.py

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/402)

add empty line after beacon

---

integration_tests/devices/comm.py
integration_tests/telecommand/comm.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/403)

Add possibility to use enumaration as parameter of SetBitrate telecomand

---

integration_tests/response_frames/common.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/404)

Correlation id in success frames

---

integration_tests/devices/comm.py
integration_tests/devices/comm_beacon.py
integration_tests/response_frames/common.py
integration_tests/telecommand/base.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/405)

Remove address from frame print

---

integration_tests/devices/comm_beacon.py

```
BeaconFrame
BP VOLT 7.25 V, 7.21 V
BP TEMP 18.44 C, 18.25 C, 17.20 C
COMM PA TEMP NOW 21.00 C LAST 20.62 C
OBC CRC 0xBFFD
GYRO UNCAL -1.18 deg/sec, -3.34 deg/sec, 0.77 deg/sec
EXPERIMENT None
!!!!!	MCU TEMP 31.51 C
!!!!!	3V3 DISTR CURRENT 162 mA
BeaconFrame
BP VOLT 7.25 V, 7.29 V
BP TEMP 16.81 C, 16.56 C, 15.70 C
COMM PA TEMP NOW 20.67 C LAST 22.42 C
OBC CRC 0xBFFD
GYRO UNCAL -1.39 deg/sec, -3.20 deg/sec, 1.04 deg/sec
EXPERIMENT None
MCU TEMP 11.98 C
3V3 DISTR CURRENT 35 mA,
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/409)

Add MCU temp and 3.3 current to beacon

---

integration_tests/experiment_type.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/407)

Fix python projection of experiment iteration result enumeration.

---

integration_tests/emulator/emulator.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/408)

WX imported only when emulator initializes

---

integration_tests/devices/comm_beacon.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/410)

Print CRC only when invalid

---

integration_tests/devices/comm_beacon.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/412)

Added COMM RX Current to Beacon Parser summary.

---

integration_tests/tools/parse_radfet.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/413)

Radfet parser

---

integration_tests/devices/comm_beacon.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/414)

Added transmitter bitrate to parsed beacon.

---

integration_tests/emulator/beacon_parser/experiment_telemetry_parser.py

Hi,
Found typo in bit count.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/415)

fix number of bits

---

integration_tests/emulator/beacon_parser/gyroscope_telemetry_parser.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/417)

Fixed integer division in Gyro temperature parsing.

---

deep_sleep/main.cpp
deep_sleep/state.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/421)

Resetting rebootToNormalCounter when receiving Comm frame

---

deep_sleep/main.cpp
integration_tests/response_frames/deep_sleep_beacon.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/422)

Beacon with rebootToNormalValue

---

deep_sleep/include/config.hpp

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/423)

Updated Deep Sleep parameters

---

integration_tests/response_frames/program_upload.py
integration_tests/telecommand/program_upload.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pw-sat2/pwsat2obc/420)

Nicer view to OPER of software upload commands
